#!/usr/bin/env bash
# Render the estate context sources into per-harness user files.
# Idempotent; rendered files are COPIES (safe if this checkout moves).
#
# Targets:
#   ~/.omp/agent/AGENTS.md   omp user context  (omp-prelude + estate brief).
#                            Deliberately shadows ~/.claude/CLAUDE.md at user
#                            scope (native provider, priority 100).
#   ~/.omp/agent/RULES.md    omp sticky rules  (invariants; re-attached near
#                            the current turn, survives compaction).
#   ~/.agents/estate.md      cross-harness copy; ~/.claude/CLAUDE.md imports it
#                            via `@~/.agents/estate.md` (verified, not written).
set -euo pipefail

PKG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAX_EST_TOKENS=2400   # estate.md budget gate (bytes/4 estimate)

est_tokens() { echo $(( $(wc -c < "$1") / 4 )); }

tokens="$(est_tokens "${PKG_DIR}/estate.md")"
if [ "$tokens" -gt "$MAX_EST_TOKENS" ]; then
  echo "FAIL: estate.md ≈ ${tokens} tokens > budget ${MAX_EST_TOKENS}. Trim it — this file taxes every session of every harness." >&2
  exit 1
fi

header() {
  printf '<!-- GENERATED by agentic/packages/context/render.sh — edit the sources in packages/context/, then re-render. -->\n\n'
}

mkdir -p "${HOME}/.omp/agent" "${HOME}/.agents"

{ header; cat "${PKG_DIR}/omp-prelude.md"; echo; cat "${PKG_DIR}/estate.md"; } \
  > "${HOME}/.omp/agent/AGENTS.md"
{ header; cat "${PKG_DIR}/invariants.md"; } \
  > "${HOME}/.omp/agent/RULES.md"
{ header; cat "${PKG_DIR}/estate.md"; } \
  > "${HOME}/.agents/estate.md"

echo "rendered: ~/.omp/agent/AGENTS.md ~/.omp/agent/RULES.md ~/.agents/estate.md (estate.md ≈ ${tokens} tokens)"

# Verify (never write) the Claude Code import line.
if ! grep -q '@~/.agents/estate.md' "${HOME}/.claude/CLAUDE.md" 2>/dev/null; then
  echo "WARN: ~/.claude/CLAUDE.md does not import the estate brief. Add this line to it:" >&2
  echo "      @~/.agents/estate.md" >&2
fi
